name: Development

on:
  push:
    branches: [development]

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:

  terraform:
    name: Terraform
    secrets: inherit
    uses: ./.github/workflows/terraform.yaml
    with:
      aws-account-id: 746669201677
      environment: development
      deployment: false
